ingress:
  enabled: true
keycloak:
  realmUrl: "https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}"
name: "${WEBAPP_NAME}"
powerbi:
  tenantId: "${POWERBI_APP_TENANT_ID}"
  clientId: "${POWERBI_APP_CLIENT_ID}"
  clientSecret: "${POWERBI_APP_SECRET}"
superset:
  apiUrl: "http://superset-web.${NAMESPACE}.svc.cluster.local/api/v1"
  superuser:
    username: "admin"
    password: "${SUPERSET_SUPERUSER_PASSWORD}"
cosmotech:
  apiUrl: "${COSMOTECH_API_URL}"
tolerations:
- key: "vendor"
  operator: "Equal"
  value: "cosmotech"
  effect: "NoSchedule"
nodeSelector:
  "cosmotech.com/tier": "services"
resources:
  limits:
    cpu: "1000m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"
webapp:
  domainName: "${CLUSTER_DOMAIN}"
  functions:
    image:
      pullPolicy: "Always"
      repository: "ghcr.io/cosmo-tech/azure-sample-webapp/webapp-functions"
    # Tolerations for hybrid deployment (cloud + on-premises):
    # On on-premises nodes, add a taint `vendor=tech:NoSchedule`
    tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
    nodeSelector:
      "cosmotech.com/tier": "services"
  publicUrl: "/${NAMESPACE}/${WEBAPP_NAME}"
  server:
    image:
      pullPolicy: Always
      repository: "ghcr.io/cosmo-tech/azure-sample-webapp/webapp-server"
    tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
    nodeSelector:
      "cosmotech.com/tier": "services"
    